image: Visual Studio 2015

environment:
  PYTHON: "C:\\Python35"
  PYTHON_VERSION: 3.5
  PYTHON_ARCH: 32
  MSVC_VERSION: "Visual Studio 14"
  LIB: C:/Program Files/Microsoft SDKs/Windows/v7.0/Include/

platform: x86

configuration: Release

init:
  - set PYTHONPATH=%PYTHON%
  - set PYTHONHOME=%PYTHON%
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -m site
  - python -m pip install -U pip setuptools wheel

install:
  - python setup.py bdist
  - python setup.py bdist_egg
  - python setup.py bdist_wheel
  - dir

# Not a project with an msbuild file, build done at install.
build: off

artifacts:
  - path: 'dist'
    type: zip
    name: py2exe-py35

# Push artefact to S3 bucket and list all
before_deploy:
  - dir dist
  #- python -c "from PySide2 import QtCore; print QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.PluginsPath)"


# Deploy build to BinTray
deploy:
  provider: BinTray
  username: alby128
  api_key:
    secure: lAocj5KA9Z9x4BefQBIgNlQJbeW4qPBfCgYVBHMyOP3NgyhnMLmvR57ZCqtCKBlQ
  subject: alby128
  repo: Syncplay
  package: Syncplay
  version: "test"
  publish: true
  override: true
    